Name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs_on:  ubuntu_latest
    steps:  
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hi Shweta from gitHub Action"
